### ISSUE TITLE
Add Google Analytics tracting

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-template-manager#7]
### Motivation

It would be great to see the traction of the site.

### Proposed solution

Add google analytics with the code: UA-69014260-7

### Additional context

Currently used on kentico.github.io so there should be no overlap.

**Comment by Simply007** [comment]
It seems like it is required to ad the path prefix of the page URL because currently, it looks like it tracks the URL: `https://kentico.github.io/cloud-template-manager/` tracks as `/`, `https://kentico.github.io/cloud-template-manager/templates` as '/templates', etc.

It is possible to hardcode it or load it from window.location in `src/services/google/google-analytics.service.ts` in around line 64+, but I am not sure, what is path location vs pathUrl.

**Comment by Enngage** [comment]
The domain is injected by Google automatically, I'm can only provide relative paths such as:

`/templates
/import-from-project
`

What I can do is manually add `cloud-template-manager` prefix to the relative URL which should achieve what you mentioned

**Comment by Simply007** [comment]
I think it is OK since you describe to me what is the difference between location vs pathUrl.

**Comment by Simply007** [comment]
Functionality adjusted in https://github.com/Kentico/cloud-template-manager/commit/ee2816ee362ff3b5de17fdee36bdfecca015cb5c
